### ISSUE TITLE
Report Generation in GitHub Actions fails on development branch

### ISSUE THREAD

**Issue by Steffengreiner** [qbicsoftware/data-model-lib#145]
**Describe the bug**
The Problem started with the [commit ](https://github.com/qbicsoftware/data-model-lib/commit/121c92ad452a3950b732fc29bc196fce665aee42) of the Template Branch into the development branch. 
Since then the report generation fails for each new commit. 

**Expected behavior**
The report generation github action should not fail and the maven site generation should include the generated documentation.

**How to Fix**
Add the necessary plugins and dependencies to the `pom.xml` of data-model-lib. This includes: 

As a dependency: 

- groovy-all (for GmavenPlus to run properly)

As a plugin repository: 
The URL to our Nexus(otherwise the groovydoc-maven-plugin won't be found) 
https://qbic-repo.qbic.uni-tuebingen.de/repository/maven-releases

To the build section: 

- maven-site-plugin (For site generation)
- maven-project-info-reports-plugin (For report generation) 
- groovydoc-maven-plugin (To include the generated reports into the project summary)

To the reporting section:

- groovydoc-maven-plugin (To include the generated reports into the project summary)

**Additional context**
This is the same issue as [#124](https://github.com/qbicsoftware/offer-manager-2-portlet/issues/124) in the offer-manager-2-portlet. 
There is also a PR ready to fix the issue in offer-manager-2-portlet [#279](https://github.com/qbicsoftware/offer-manager-2-portlet/pull/279)

**Comment by jenniferboedker** [comment]
Can this be closed?

**Comment by Steffengreiner** [comment]
yes i think so
