### ISSUE TITLE
GroovyCastException when using the ProductId Builder

### ISSUE THREAD

**Issue by jenniferboedker** [qbicsoftware/data-model-lib#186]
**Describe the bug**
When trying to create a productId with its Builder after compiling an error is thrown

**To Reproduce**
1. Run the tests in `ProductIdSpec`
2. Observe them run locally
3. Observe them fail with `mvn clean package`

**Expected behavior**
The test should run properly.

**Additional context**
When using the builder in an external project e.g. Offer-Manager, you can observe the tests using the Builder will fail directly

**Comment by jenniferboedker** [comment]
Tests were introduced with #187

**Comment by sven1103** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GroovyCastException when using the ProductId Builder #186](https://trello.com/c/NmfTrOeU/722-groovycastexception-when-using-the-productid-builder-186)
