### ISSUE TITLE
Map created from pooled Nanopore data is incorrect

### ISSUE THREAD

**Issue by wow-such-code** [qbicsoftware/data-model-lib#19]
example with two pooled samples:
```
{QMFPJ005AE=
{fast5fail=life.qbic.datamodel.datasets.datastructure.folders.DataFolder(children:[life.qbic.datamodel.datasets.datastructure.files.DataFile(fileType:fast5, relativePath:20200605_1435_1-E3-H3_PAE42978_e57ee0a6/fast5_fail/QMFPJ007AU/PAE42978_fail_barcode23_c6bc1a3f_0.fast5, name:PAE42978_fail_barcode23_c6bc1a3f_0.fast5)],
...
QMFPJ007AU=
{fast5fail=life.qbic.datamodel.datasets.datastructure.folders.DataFolder(children:[life.qbic.datamodel.datasets.datastructure.files.DataFile(fileType:fast5, relativePath:20200605_1435_1-E3-H3_PAE42978_e57ee0a6/fast5_fail/QMFPJ007AU/PAE42978_fail_barcode23_c6bc1a3f_0.fast5, name:PAE42978_fail_barcode23_c6bc1a3f_0.fast5)],...
```
Values for different keys are the same, so correct for one sample, but wrong for the other.

The problem is not in the core-utils-lib parser, but most likely somewhere here:
https://github.com/qbicsoftware/data-model-lib/blob/615d2a161eac5e11605198502aa0057cf7054505/src/main/groovy/life/qbic/datamodel/datasets/OxfordNanoporeMeasurement.groovy#L241

**Comment by KochTobi** [comment]
The output was created using 
`convertedExperiment.getMeasurements().get(0).getRawDataPerSample(convertedExperiment)`

**Comment by KochTobi** [comment]
The output looks like the `children` list instance is overwritten and the newest is returned in each measurement.

**Comment by KochTobi** [comment]
The issue might originate in the creation of the folders map in https://github.com/qbicsoftware/data-model-lib/blob/master/src/main/groovy/life/qbic/datamodel/datasets/OxfordNanoporeMeasurement.groovy#L116
