### ISSUE TITLE
Fix MaxQuant folder structure

### ISSUE THREAD

**Issue by jenniferboedker** [qbicsoftware/data-model-lib#253]
**Is your feature request related to a problem? Please describe.**
The current MaxQuant folder structure is not correct.

**Describe the solution you'd like**
The left structure shows how the structure currently looks like and the right structure shows how it supposed to look.
![Screenshot 2021-08-09 at 12 53 34](https://user-images.githubusercontent.com/20778777/128696966-cf744a76-2a65-4c8e-84d0-1bd576700a0e.png)

Don't forget that the Parser in core-utils lib might need to be adjusted as well

**Update**
See the discussion below: the experimentalDesignTemplate.txt should be contained within the txt folder.

**Comment by jenniferboedker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update MaxQuant data structure](https://trello.com/c/qDmC89vI/927-update-maxquant-data-structure)

**Comment by jenniferboedker** [comment]
` I have also added some random letters to the name of the big folder: maxquant_result_QXXXXabcd; because several result folders corresponding either to the same project or to different projects are store together and they need to have different names e.g. maxquant_result_0985_R01R10, maxquant_result_0985_R11R20.`

**Comment by KochTobi** [comment]
What is the reasoning behind moving the `experimentalDesignTemplate.txt` out of the `txt` folder?

**Comment by jenniferboedker** [comment]
It turns out the figure above is correct. 

MaxQuant saves the file 2 times. So we could additionally extend the figure and also add the experimentalDesignTemplate.txt inside of the txt folder. If we decide to only store one, then the provided is preferred.

**Comment by jenniferboedker** [comment]
Updated the documentation with https://github.com/qbicsoftware/data-model-lib/pull/260

**Comment by KochTobi** [comment]
This can be closed, correct?
